# Generated by Django 3.0.7 on 2020-07-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/%Y/%m/%d/')),
                ('Body', models.CharField(max_length=3000)),
            ],
        ),
    ]
