# Generated by Django 3.0.7 on 2020-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_delete_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.png', upload_to='users/%Y/%m/%d/'),
        ),
    ]
