# Generated by Django 3.0.7 on 2020-08-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200817_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/no_image.png', upload_to='media/%Y/%m/%d/'),
        ),
    ]
