# Generated by Django 3.0.7 on 2020-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200817_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, default='media/images/no_image.png', upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/images/no_image.png', upload_to='media/%Y/%m/%d/'),
        ),
    ]
