# Generated by Django 3.0.7 on 2020-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200701_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d/'),
        ),
    ]
