# Generated by Django 3.0.7 on 2020-07-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Body',
            field=models.TextField(),
        ),
    ]
