# Generated by Django 3.0.7 on 2020-07-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200711_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='body',
            new_name='Body',
        ),
    ]
