# Generated by Django 3.0.7 on 2020-07-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200711_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
