# Generated by Django 3.0.7 on 2020-07-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_aboutme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
